# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: eef60f5a7d9e6efbd3908e679362e09e7fe94ec17fd7c4694f5e8fa95d0f00ef089578304d28d9efa5004dd64cccdfe02d3fe3a9c155697f2caee265b3e0efd1

test:
  secret_key_base: 98df76f9c92d678c972c45123c6b22489b9e7f767302a4735addf0abfc91ea81d41c76d38224db20f8f2694bf758c983905310f52142a9e576630e6ca6dd9530

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
